<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Missum.Ai.Server.Core</RootNamespace>
    <AssemblyName>Missum.Ai.Server.Core</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Missum.Ai.Contracts\Missum.Ai.Contracts.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="DocumentFormat.OpenXml" />
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="PdfPig" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" />
  </ItemGroup>
  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>Missum.Ai.Server.Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>
</Project>
